account default
host smtp.gmail.com
port 465
auth login
user Containertest125@gmail.com
password dzxokwxoflgzuquw
from Containertest125@gmail.com
tls on
tls_starttls off
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile /var/log/msmtp.log
